language: scala
jdk:
- openjdk8
- openjdk11
sudo: false
script:
- sbt "+ test" "+ tests/run"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
